import { FileNode } from './types';

export const COLORS = {
  bg: '#1A1A1A',
  surface: '#262626',
  border: 'rgba(255, 255, 255, 0.08)',
  text: '#F0F0F0',
  sub: '#A0A0A0',
  accent: '#E2E8F0', // Slate-200
  laser: '#00FF41',
};

// 对应 S.P.E.C.I.A.L. 流程
export const PROCESSING_STEPS = [
  {
    main: "S.P.E.C. - 定义规格",
    sub: "正在像写日记一样解析需求说明书..."
  },
  {
    main: "INTENT - 确立意图",
    sub: "AI 时代的掠夺者拒绝背诵语法..."
  },
  {
    main: "ARCHITECT - 积木组装",
    sub: "正在调度 AI 专家团队构建架构..."
  },
  {
    main: "LAUNCH - 点火起航",
    sub: "消除创意与代码的摩擦力..."
  }
];

export const MANIFESTO_QUOTES = [
  {
    text: "用积木组装软件。",
    author: "Porter，18岁 S.P.E.C.I.A.L. ARCHITECT"
  },
  {
    text: "如果你能说清楚你的需求，你就已经完成了软件的开发。",
    author: "SPEC Coding"
  },
  {
    text: "一个人，凭借 S.P.E.C.I.A.L. 积木架构，就能调度成千上万个 AI 开发专家。",
    author: "超级个体"
  }
];

export const MOCK_FILE_TREE: FileNode[] = [
  {
    name: "generated_project_20260102",
    type: "folder",
    children: [
      { name: "main.py", type: "file" },
      { name: "spec.md", type: "file" },
      { name: "plan.md", type: "file" },
      { name: "requirements.txt", type: "file" },
      { name: "README.md", type: "file" }
    ]
  }
];

export const MOCK_CODE_CONTENT = `import sys
from PyQt6.QtWidgets import QApplication, QMainWindow, QLabel
from core.spec_parser import SpecParser

class SpecialArchitectApp(QMainWindow):
    """
    S.P.E.C.I.A.L. 架构演示应用
    Generated by SpecKit Lite
    """
    def __init__(self):
        super().__init__()
        self.setWindowTitle("S.P.E.C.I.A.L. Architect")
        self.setGeometry(100, 100, 800, 600)
        
        # 初始化核心组件
        self.parser = SpecParser(config="spec.md")
        self.setup_ui()

    def setup_ui(self):
        label = QLabel("用积木组装软件 - Porter", self)
        label.adjustSize()
        label.move(50, 50)
        
        print(f"System initialized. Mode: {self.parser.mode}")

if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = SpecialArchitectApp()
    window.show()
    sys.exit(app.exec())`;