openapi: 3.0.3
info:
  title: AI Code Flow API
  description: AI-powered code generation system with process transparency and educational feedback
  version: 1.0.0
  contact:
    name: AI Code Flow Team

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.ai-code-flow.com
    description: Production server

paths:
  /health:
    get:
      summary: Health check endpoint
      description: Verify system health and configuration status
      operationId: getHealth
      responses:
        '200':
          description: System is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '500':
          description: System configuration error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /generate-code:
    post:
      summary: Generate code from natural language request
      description: |
        Process a natural language code generation request through the three-phase workflow:
        Specify → Plan → Implement. Returns streaming response with progressive status feedback and content replay.
      operationId: generateCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CodeGenerationRequest'
      responses:
        '200':
          description: Code generation completed successfully
          content:
            text/event-stream:
              schema:
                $ref: '#/components/schemas/StreamingResponse'
        '400':
          description: Invalid request or VENV_NOT_ACTIVATED error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too many concurrent requests (system at capacity)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error or AI engine failure
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /projects/{projectId}:
    get:
      summary: Get generated project details
      description: Retrieve metadata and file structure for a generated project
      operationId: getProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique project identifier
      responses:
        '200':
          description: Project details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProjectDetails'
        '404':
          description: Project not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /projects/{projectId}/download:
    get:
      summary: Download generated project files
      description: Download a ZIP archive containing all project files
      operationId: downloadProject
      parameters:
        - name: projectId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Unique project identifier
      responses:
        '200':
          description: Project files download initiated
          content:
            application/zip:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              schema:
                type: string
                example: 'attachment; filename="snake_game_20260101_123456.zip"'
        '404':
          description: Project not found or not ready for download
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    CodeGenerationRequest:
      type: object
      required:
        - user_input
      properties:
        user_input:
          type: string
          minLength: 1
          maxLength: 1000
          description: Natural language request for code generation (supports Chinese)
          example: "帮我写个贪吃蛇"
      additionalProperties: false

    StreamingResponse:
      description: Server-Sent Events stream for progressive code generation status and content replay
      type: string
      enum:
        - phase_update
        - content_chunk
        - completion
        - error
      example: |
        event: phase_update
        data: {"phase": "specify", "message": "正在分析需求，定义功能边界..."}

        event: content_chunk
        data: {"type": "thinking", "content": "分析用户需求：贪吃蛇游戏需要..."}

        event: content_chunk
        data: {"type": "code", "content": "import pygame\n\n# 初始化游戏..."}

        event: completion
        data: {"project_id": "123e4567-e89b-12d3-a456-426614174000", "status": "success"}

    HealthResponse:
      type: object
      required:
        - status
        - timestamp
        - version
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
          example: healthy
        timestamp:
          type: string
          format: date-time
          example: "2026-01-01T12:00:00Z"
        version:
          type: string
          example: "1.0.0"
        config_valid:
          type: boolean
          description: Whether backend/config.json is present and valid
          example: true
        venv_active:
          type: boolean
          description: Whether running in correct virtual environment
          example: true
      additionalProperties: false

    ProjectDetails:
      type: object
      required:
        - id
        - project_name
        - created_at
        - file_structure
        - syntax_validated
      properties:
        id:
          type: string
          format: uuid
          example: "123e4567-e89b-12d3-a456-426614174000"
        project_name:
          type: string
          example: "snake_game_20260101_123456"
        created_at:
          type: string
          format: date-time
          example: "2026-01-01T12:00:00Z"
        file_structure:
          $ref: '#/components/schemas/FileStructure'
        dependencies:
          type: array
          items:
            type: string
          example: ["pygame"]
        total_files:
          type: integer
          minimum: 1
          example: 3
        total_size_bytes:
          type: integer
          minimum: 0
          maximum: 10485760  # 10MB
          example: 15360
        syntax_validated:
          type: boolean
          description: Whether all Python files passed AST validation
          example: true
        main_file:
          type: string
          description: Path to the main executable file
          example: "main.py"
      additionalProperties: false

    FileStructure:
      type: object
      required:
        - type
        - name
      properties:
        type:
          type: string
          enum: [file, directory]
        name:
          type: string
        size:
          type: integer
          minimum: 0
          description: File size in bytes (only for files)
        language:
          type: string
          description: Programming language (only for files)
          example: "python"
        children:
          type: array
          items:
            $ref: '#/components/schemas/FileStructure'
          description: Child files/directories (only for directories)
      additionalProperties: false
      example:
        type: "directory"
        name: "snake_game_20260101_123456"
        children:
          - type: "file"
            name: "main.py"
            size: 1234
            language: "python"
          - type: "file"
            name: "README.md"
            size: 567
            language: "markdown"

    ErrorResponse:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
          enum:
            - VENV_NOT_ACTIVATED
            - CONFIG_MISSING
            - INVALID_REQUEST
            - AI_ENGINE_ERROR
            - TIMEOUT_ERROR
            - VALIDATION_ERROR
            - SYSTEM_OVERLOAD
            - PROJECT_NOT_FOUND
          example: AI_ENGINE_ERROR
        message:
          type: string
          description: Human-readable error message in Chinese
          example: "AI 引擎暂时不可用，请稍后重试"
        timestamp:
          type: string
          format: date-time
          example: "2026-01-01T12:00:00Z"
        request_id:
          type: string
          format: uuid
          description: Request identifier for debugging
        retry_after:
          type: integer
          minimum: 0
          description: Seconds to wait before retrying
      additionalProperties: false

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for authentication (future use - currently open access)